spring:
  application:
    name: audio-service
  liquibase:
    change-log: classpath:/db/changelog.yml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: audio
    show-sql: true
  datasource:
    url:
    username:
    password:

event:
  bootstrap-servers:
  service-name: ${spring.application.name:audio-service}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka
