spring:
  application:
    name: audio-service
  liquibase:
    change-log: classpath:/db/changelog.yml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: audio
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

event:
  bootstrap-servers: ${KAFKA_URL}
  service-name: ${spring.application.name:audio-service}

domain:
  genre-source: domain/genres.csv

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}
