spring:
  application:
    name: audio-service
  liquibase:
    change-log: classpath:/db/changelog.yml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: audio
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/tunepoint
    username: tunepoint
    password: tunepoint

event:
  bootstrap-servers: localhost:9092
  service-name: ${spring.application.name:audio-service}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka
